Fundamentos de Programación y Scripting
Laboratorio 1
Percy Jacobs

1. Vectores y Matrices
```{r}
student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

# vector de vectores
students_vector <- c(student_1, student_2, student_3, student_4, student_5)

# matriz
students_matrix <- matrix(students_vector, nrow = 5, byrow = TRUE)
students_matrix

```


2. Nombrado de una matriz
```{r}
name_students <- c("Lily Brown","Davis Moore","Susan Taylor","Mike Jones","Tom Hill")
name_courses_legal_age <- c("TIC","Accounting","Psychology","Ethics","Legal_age")

rownames(students_matrix) = name_students
colnames(students_matrix) = name_courses_legal_age

students_matrix
```


3. Sumas de notas
```{r}
total_grade_student <- rowSums(students_matrix[,1:4])
total_grade_student

result_students <- cbind(students_matrix, total_grade_student)
result_students

```


4. Seleccionando elementos de una matriz
```{r}
selected_elements <- result_students[c(1,3,5),c(2,4)]
print(selected_elements)
```


5. Data Frames
```{r}
students_grades_df <- data.frame(result_students)
students_grades_df

subset(students_grades_df, (Accounting > 80) & (Legal_age == TRUE))
```


6. Funciones, Condicionales y Bucles
```{r}
students_projection <- function() {
  for (i in 1:nrow(result_students)) {
    for (j in 1:ncol(result_students[,1:4])) {
      if(result_students[i,j] <= 45){
        print("Student at risk")
      }else if(result_students[i,j] > 45 & result_students[i,j] < 61){
        print("Student may be approved")
      }else if(result_students[i,j] >= 61){
        print("Student approved")
      }
    }
  }
}

students_projection()
```


7. Data frames y lapply
```{r}
index_education <- function(grade){
  res <- (1+(grade/100))/2
  return(res)
}

all_students_grade <- students_grades_df[,1:4]
lapply(all_students_grade, index_education)

```


8. Math utilities
```{r}
score_mean <- colMeans(students_grades_df[,1:4])
score_mean
```

